import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { TooltipProvider } from "@/components/ui/tooltip";
import Footer from "@/components/common/Footer";
import { Quote } from "@/components/common/Quote";
import { ThemeProvider } from "next-themes";
import OnekoCat from "@/components/common/OnekoCat";
import { ViewTransitions } from 'next-view-transitions'
import { ReactLenis } from '@/lib/lenis'

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-ibm-plex-mono",
  display: "swap",
});



export const metadata: Metadata = {
  title: "Kunal Roy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${ibmPlexMono.className} antialiased`}
          suppressHydrationWarning
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange={false}
            storageKey="theme"
          >
            <ReactLenis root>
              <TooltipProvider>
                <Navbar />
                {children}
                <OnekoCat />
                <Quote />
                <Footer />
              </TooltipProvider>
            </ReactLenis>
          </ThemeProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
